# Configuração do datasource
spring:
  datasource:
    url: jdbc:mysql://meli-item-details-api-db:3306/spring_template
    username: spring_template
    password: spring_template

# Configuração do JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect

# Ativação do perfil de produção
  config:
    activate:
      on-profile: prod