spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev

  doc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html


app:
  name: meli-item-details-api

server:
  servlet:
    context-path: /api/v1

