# Configuração do datasource
spring:
  datasource:
    initialization-mode: always
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:spring-template-db;DB_CLOSE_DELAY=-1
    username: spring_template
    password: spring_template

# Configuração do JPA/Hibernate
  config:
    activate:
      on-profile: dev
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

# Configuração do H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console


logging:
  level:
    root: INFO  # Desliga todos os logs