spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html


app:
  name: meli-item-details-api

server:
  servlet:
    context-path: /api/v1

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      productService:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        register-health-indicator: true
        record-exceptions:
          - java.lang.Exception
        ignore-exceptions:
          - com.pablords.meli.itemdetail.domain.application.exception.NotFoundException

  ratelimiter:
    instances:
      productService:
        limit-for-period: 50
        limit-refresh-period: 1m
        timeout-duration: 5s
        register-health-indicator: true

# Management endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers,ratelimiters
  endpoint:
    health:
      show-details: always

